name: Conveyor
inputs:
  command:
    type: string
    required: true
  signing_key:
    type: string
    required: true
  extra_flags:        
    type: string
    required: false
  cache_key:
    type: string
    required: false
    default: 'conveyor'
  cache_path:
    type: string
    required: false
    default: '.conveyor'  
  conveyor_version:
    type: string
    required: false
    default: '7.1'
        
runs:
  using: "composite"
  
  steps:
    - name: Load cache
      id: load-cache
      uses: actions/cache@v3
      with:
        key: ${{ inputs.cache_key }}-${{github.run_id }}
        path: ${{ inputs.cache_path }}
        restore-keys: ${{ inputs.cache_key }}
        
    - name: Download Conveyor
      if: ${{ steps.load-from-cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        wget https://downloads.hydraulic.dev/conveyor/conveyor-${{ inputs.conveyor_version }}-linux-amd64.tar.gz
        mkdir -p ${{ inputs.cache_path }}/install
        tar xzvf conveyor-${{ inputs.conveyor_version }}-linux-amd64.tar.gz -C ${{ inputs.cache_path }}/install      
          
    - name: Run Conveyor
      env:
        SIGNING_KEY: ${{ inputs.signing_key }}
      shell: bash
      run: |
        if [ -z "$SIGNING_KEY" ]; then
          KEY="-Kapp.sign=false"
        else
          KEY="-Kapp.signing-key=$SIGNING_KEY"
        fi
        PATH="$PATH:${{ inputs.cache_path }}/install/conveyor-${{ inputs.conveyor_version }}/bin"
        conveyor --cache-dir=${{ inputs.cache_path }}/cache --agree-to-license=1 "$KEY" ${{ inputs.extra_flags }} ${{ inputs.command }}    
