name: Test cache

on: [workflow_dispatch]
jobs:  
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run Conveyor     
        uses: ./action
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: make       
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1

      - name: Run Conveyor again 
        uses: ./action
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: task-dependencies site       
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
