name: Debugging
on: workflow_dispatch
jobs:
  test:
    runs-on: windows-2019
    steps:
      - name: Test
        env:
          ENV_SECRET: ${{ secrets.SUPER_SECRET }}
        run: |
          echo $Env.ENV_SECRET
          echo Testing
          echo Testing more
        
