name: Flutter Deploy

on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Download Conveyor
        run: |
          wget https://downloads.hydraulic.dev/conveyor/conveyor-7.1-linux-amd64.tar.gz
          mkdir install
          tar xzvf conveyor-7.1-linux-amd64.tar.gz -C install
          echo "$PWD/install/conveyor-7.1/bin" >> $GITHUB_PATH
          
      - name: Setup SSH
        env:
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        run: |
          echo "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
          
      - name: Run Conveyor
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          COPY_TO: ${{ secrets.COPY_TO }}
        run: conveyor --agree-to-license=1 -Kapp.signing-key="$SIGNING_KEY" -Kapp.site.copy-to="$COPY_TO" make copied-site
