name: Flutter Deploy

on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Download macOS ARM build
        uses: actions/download-artifact@v3
        with:
          name: build-macos-aarch64
          path: ./artifacts
          
      - name: Download macOS AMD64 build
        uses: actions/download-artifact@v3
        with:
          name: build-macos-amd64
          path: ./artifacts
          
      - name: Download Windows build
        uses: actions/download-artifact@v3
        with:
          name: build-windows-amd64
          path: ./artifacts
          
      - name: Download macOS AMD64 build
        uses: actions/download-artifact@v3
        with:
          name: build-linux-amd64
          path: ./artifacts          
        
      - name: Set up SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          
      - name: Run Conveyor     
        uses: leo-hydraulic/flutter-demo@v1
        with:
          command: make copied-site
          extra_flags: -Kapp.site.copy-to="${{ secrets.COPY_TO }}"
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
