name: Flutter Deploy

on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Download Conveyor
        run: |
          wget https://downloads.hydraulic.dev/conveyor/conveyor-7.1-mac-amd64.zip
          unzip conveyor-7.1-mac-amd64.zip -d install
          
      - name: Run Conveyor
        run: install/Conveyor.app/Contents/MacOS/conveyor make site
