name: Error log

on: [workflow_dispatch]
jobs:  
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run Conveyor     
        uses: hydraulic-software/conveyor/actions/build@v11.4
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_flags: "-Kapp.machines=none"
          command: make copied-site          
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
      - if: ${{ failure() }}
        name: 'Check tree'
        run: |
          tree
          tree ~          
      - if: ${{ failure() }}
        name: 'Upload Conveyor log'
        uses: actions/upload-artifact@v3
        with:
          name: conveyor-log
          path: .cache/hydraulic/conveyor/logs/log.latest.txt
